# $$ Assignment No:3 $$

In [1]:
# Q1

try:
    z=5/0
    
except ZeroDivisionError as error:
        # Output expected ZeroDivisionErrors.
        print(error)

division by zero


In [2]:
# Q2
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for z in objects:
            print(f"{i} {j} {z}")

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [10]:
# Q3 
import numpy as np

def matrix(vector, n,n1):
    
    if n1=='dec':
        final= np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(n,n)
    elif n1== 'inc':
        final = np.array([x**i for x in vector for i in range(n)]).reshape(n,n)
    
    return final
# vector=(1,2,3,4,5)
# n=5

# INPUT
n = int(input("Enter the number"))
print("Enter the vector")
vector=[]
for i in range(n):
    a = int(input(""))
    vector.append(a)
print("Vector :",vector)

#Calling the fun for increasing order
inc = matrix(vector,n,"inc")
dec = matrix(vector,n,"dec")

print("Increasing order: \n",inc)
print("Decreasing order: \n",dec)

Enter the number5
Enter the vector
1
2
3
4
5
Vector : [1, 2, 3, 4, 5]
Increasing order: 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Decreasing order: 
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
